---
- name: Converge
  hosts: all

  pre_tasks:
    - name: create test_usr
      become: yes
      user:
        name: test_usr
        state: present
        home: /home/test_usr
        createhome: yes

  roles:
    - role: ansible-role-pin-to-launcher
      pin_to_launcher: dockbarx
      pin_to_launcher_favorites:
        - application: test-app.desktop
        - application: test-app2.desktop
          application_id: test-id
          when_desktop: dockbarx
        - application: test-app3.desktop
          when_desktop: unity
        - application: ''
        - application: '{{ None }}'
        - application: '{{ omit }}'
        - {}
    - role: ansible-role-pin-to-launcher
      pin_to_launcher: unity
      pin_to_launcher_favorites:
        - application: test-app3.desktop
        - application: test-app4.desktop
          when_desktop: unity
        - application: test-app5.desktop
          when_desktop: dockbarx
        - application: ''
        - application: '{{ None }}'
        - application: '{{ omit }}'
        - unity: running-apps
        - unity: ''
        - unity: '{{ None }}'
        - unity: '{{ omit }}'
        - {}
